Livraison 3 dernières actualités sur page Home
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #10
Opened 2023-04-20 22:34 UTC by BENJAMIN-SAUSSAYE

2023-04-21 07:55 UTC, PAimery submitted a review, later dismissed

2023-04-21 08:53 UTC, Zakari-B requested changes

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_card_actuality.html.twig
> +{% if (smallcard ?? false) == false %}
Euh, pourquoi ?

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_card_actuality.html.twig
> +					<span>{{ actuality.creation_date|date("m/d/Y", "Europe/Paris")  }}</span>
Site français avec format de date anglais ?

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_card_actuality.html.twig
> +				<a href="/news/show?id={{ actuality.id }}" role="button" class="secondary">DÉTAIL</a>
Détails plutôt ?

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_card_actuality.html.twig
> +		<small>{{ actuality.creation_date|date("m/d/Y", "Europe/Paris")  }}</small>
Idem date

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_card_actuality.html.twig
> +		<a href="/news/show?id={{ actuality.id }}" role="button" class="secondary">DÉTAIL</a>
Idem détails

2023-04-21 08:53 UTC, Zakari-B commented on src/View/Component/_navbar.html.twig
> +			<a href="/actualitees">ACTUALITÉS</a>
L'un est bien orthographié, pas l'autre. actualites.

2023-04-21 10:39 UTC, BENJAMIN-SAUSSAYE commented on src/Model/ActualityManager.php
> +        $query = 'SELECT * FROM ' . self::TABLE . ' ORDER BY creation_date ASC LIMIT 3';
oui :(' désolé

2023-04-21 10:41 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_card_actuality.html.twig
> +		<a href="/news/show?id={{ actuality.id }}" role="button" class="secondary">DÉTAIL</a>
dans l'exemple Item on utilise show pour afficher le détail je suis parti sur la même logique

2023-04-24 11:50 UTC, PAimery submitted a review, later dismissed

2023-04-24 14:19 UTC, sblondeau approved these changes

2023-04-26 14:31 UTC, PAimery approved these changes

2023-04-26 15:07 UTC, PAimery approved these changes

2023-04-26 16:50 UTC, merged