Premire version pour l'affichage du détail d'une actualité.
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #12
Opened 2023-04-21 14:54 UTC by BENJAMIN-SAUSSAYE

2023-04-24 11:51 UTC, PAimery approved these changes

2023-04-24 14:22 UTC, sblondeau requested changes

2023-04-24 14:22 UTC, sblondeau commented on public/assets/images/actualities/candidature.jpg
fichier à retirer non ?

2023-04-24 14:22 UTC, sblondeau commented on src/View/Actuality/show.html.twig
> +                {% if actuality.image_path is not empty %}
plutot gérer une image placeholder si pas d'image en bdd

2023-04-24 14:37 UTC, BENJAMIN-SAUSSAYE commented on public/assets/images/actualities/candidature.jpg
oui

2023-04-24 14:38 UTC, BENJAMIN-SAUSSAYE commented on src/View/Actuality/show.html.twig
> +                {% if actuality.image_path is not empty %}
ok je reprends cette partie

2023-04-24 14:59 UTC, PAimery approved these changes

2023-04-24 15:36 UTC, sblondeau approved these changes

2023-04-26 14:34 UTC, PAimery approved these changes

2023-04-26 14:40 UTC, merged