S02 us01 caractere
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #17
Opened 2023-04-25 14:46 UTC by Justinesvr

2023-04-25 15:24 UTC, PAimery requested changes

2023-04-25 15:24 UTC, PAimery commented on public/assets/css/caractere.css
> +    margin: -150px auto;
Attention pixels

2023-04-26 12:52 UTC, PAimery approved these changes

2023-04-26 14:24 UTC, sblondeau approved these changes

2023-04-26 14:24 UTC, merged