liste des membres
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #29
Opened 2023-04-27 12:58 UTC by PAimery

2023-04-27 13:27 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-27 13:27 UTC, BENJAMIN-SAUSSAYE commented on src/Controller/AdminMemberController.php
> +/**
retirer les commentaires

2023-04-27 13:27 UTC, BENJAMIN-SAUSSAYE commented on src/routes.php
> +    'administration/membres/liste' => ['AdminMemberController', 'index'],
membres sans le liste suffira

2023-04-27 14:17 UTC, BENJAMIN-SAUSSAYE submitted a review, later dismissed

2023-04-27 14:26 UTC, sblondeau requested changes

2023-04-27 14:26 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
> +							<form action="/administration/actualites/supprimer" method="POST">
ouch attention, mauvais copier-coller tu cibles la suppression des actus là !

2023-04-27 14:26 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
> +								<input type="hidden" id="id" name="id" value="{{ actuality.id }}">
idem

2023-04-27 14:26 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
> +							<form action="/administration/actualites/modifier" method="POST">
idem

2023-04-27 14:26 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
> +							<form action="/administration/actualites/modifier" method="POST">
et pour se rendre sur la page modifier, un simple lien href="/administration/members/modifier?id=" {{ member.id }}

2023-04-28 07:54 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-28 08:17 UTC, sblondeau requested changes

2023-04-28 08:17 UTC, sblondeau commented on src/View/Admin/Member/index.html.twig
>  								<button class="primary outline" role="link">
le contraire ! /administration/membre  et member.id

2023-04-28 08:37 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-28 08:54 UTC, sblondeau requested changes

2023-04-28 08:54 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +        $members = $memberManager->selectAll();
selectAll('lastname'); (ou firstname)
=> permet de trier alphabétiquement les membres, c'est bien plus pratique pour l'admin quand il doit retrouver qq'un dans la liste ;-)

2023-04-28 09:17 UTC, rubenk3 submitted a review, later dismissed

2023-04-28 09:23 UTC, sblondeau submitted a review, later dismissed

2023-04-28 10:33 UTC, merged