S01U10-Création de la page News index
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #3
Opened 2023-04-13 14:46 UTC by BENJAMIN-SAUSSAYE

2023-04-14 07:33 UTC, Justinesvr reviewed
ok for me

2023-04-14 08:58 UTC, Zakari-B submitted a review, later dismissed

2023-04-18 09:44 UTC, PAimery submitted a review, later dismissed

2023-04-18 10:19 UTC, sblondeau requested changes

2023-04-18 10:19 UTC, sblondeau commented on public/assets/css/news.css
> +    margin-bottom: calc(var(--block-spacing-vertical) * .33);
non pas de .33, mais plutot / 3 sinon tu as une valeur approximative

2023-04-18 10:19 UTC, sblondeau commented on public/assets/css/news.css
> +    margin-top: calc(var(--block-spacing-vertical) * .66);
idem * 2 /3

2023-04-18 10:19 UTC, sblondeau commented on public/assets/css/news.css
> +    padding: 0 0 0 calc(var(--spacing)* 0.66);
idem

2023-04-18 10:19 UTC, sblondeau commented on public/assets/css/news.css
> +    padding: calc(var(--spacing)* 0.26) calc(var(--spacing)* 0.26);
le 0.26 ça s'appelle de la bidouille :D 
pourquoi pas 0.54896 ? :p

2023-04-18 10:19 UTC, sblondeau commented on src/View/News/index.html.twig
> +    <headder>
header

2023-04-18 10:19 UTC, sblondeau commented on src/Controller/NewsController.php
> +    public function show(int $id): string
c'est pas cette US ça

2023-04-18 10:19 UTC, sblondeau commented on src/Controller/NewsController.php
> +        $newslist = $newsManager->selectAll('creation_date');
et donc on aura un ActualityController
$actualityManager
$actualities = $actualityManager->selectAll('creation_date') ... etc

2023-04-18 10:19 UTC, sblondeau commented on src/Controller/NewsController.php
> +        return $this->twig->render('News/index.html.twig', ['newslist' => $newslist]);
'actualities' => $actualities

2023-04-18 10:19 UTC, sblondeau commented on database.sql
> +CREATE TABLE `news` (
news étant invariable au pluriel (et on nomme pas les tables au pluriel), fais en sorte de ne pas l'utiliser
renomme tout en actuality ça sera bien plus simple
en plus "new" étant un mot clé réservé de PHP ça évitera bien des confusions ;-)

2023-04-18 10:19 UTC, sblondeau commented on database.sql
> +    CURRENT_TIMESTAMP(),
tu as déjà mis CURRENT_TIMESTAMP() en default, pas la peine de le remettre là
ou alors choisi des dates passées en dur

2023-04-18 10:19 UTC, sblondeau commented on public/assets/css/images/empreintechienblanc_horiz.png
ça apporte vraiment qq  chose à votre design d'avoir une image en vertical et une autre en horizontal ? 
vous cherchez la complication :p

2023-04-18 10:19 UTC, sblondeau commented on src/Model/NewsManager.php
> +    public const TABLE = 'news';
actualityManager
TABLE = 'actuality'

2023-04-18 10:19 UTC, sblondeau commented on src/View/News/index.html.twig
> +        {% for news in newslist %}
for actuality in actualities  (c'est quand meme plus clair ;-) )

2023-04-18 10:19 UTC, sblondeau commented on src/routes.php
> +    'news'  => ['NewsController', 'index'],
'actualites' (nom de route en français) => ['ActualityController'...

2023-04-18 10:22 UTC, Zakari-B requested changes
Ton dossier images est à l'intérieur du dossier css alors qu'il devrait être dans assets.

2023-04-18 13:58 UTC, PAimery approved these changes

2023-04-18 15:10 UTC, sblondeau commented on database.sql
> +CREATE TABLE `Actuality` (
actuality (pas de majuscule)

2023-04-18 15:10 UTC, sblondeau commented on database.sql
> +INSERT INTO `Actuality` (
idem

2023-04-18 15:11 UTC, sblondeau commented on src/Model/ActualityManager.php
> +    public const TABLE = 'Actuality';
actuality

2023-04-18 15:12 UTC, sblondeau commented on src/View/Actuality/index.html.twig
> +	<section class="container">
une balise main plutot ?

2023-04-19 08:51 UTC, PAimery approved these changes

2023-04-19 13:19 UTC, sblondeau requested changes

2023-04-19 13:19 UTC, sblondeau commented on public/assets/css/actuality.css
> +}
des répétitions, une idée de refacto: 

article > footer {
    flex-direction: var(--flex-direction, row-reverse);
    padding-inline: var(--padding-start, var(--spacing)) var(--padding-end, 0);

    background-image: linear-gradient(
        to var(--direction, right),
        var(--intermadiate) 30%,
        var(--primary) 70%
    );
}

article:nth-child(odd) > footer {
    --direction: right;
    --padding-start: var(--spacing);
    --padding-end: 0;
    --flex-direction: row;
)

2023-04-19 16:40 UTC, PAimery approved these changes

2023-04-20 07:06 UTC, sblondeau approved these changes

2023-04-20 07:07 UTC, merged