S03 us12 add event
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #35
Opened 2023-04-28 09:00 UTC by Justinesvr

2023-04-28 15:06 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-28 15:06 UTC, BENJAMIN-SAUSSAYE commented on src/Model/EventManager.php
> +        $statement->bindValue('date', $event['date'], PDO::PARAM_INT);
PARAM INT pour la date a changer

2023-05-01 20:27 UTC, sblondeau requested changes

2023-05-01 20:27 UTC, sblondeau commented on src/Model/EventManager.php
> +        $statement->bindValue('date', $event['date'], PDO::PARAM_INT);
@BENJAMIN-SAUSSAYE ne passe pas en Reviewed s'il reste des choses à modifier. Mets en "Requested changes"

2023-05-02 07:50 UTC, PAimery submitted a review, later dismissed

2023-05-02 08:19 UTC, Zakari-B requested changes

2023-05-02 08:19 UTC, Zakari-B commented on src/Controller/AdminEventController.php
> +                return null;
Pas de return null.

2023-05-02 08:19 UTC, Zakari-B commented on src/Model/EventManager.php
> +        $statement->bindValue('date', $event['date'], PDO::PARAM_STR);
Ca n'est pas une STR ici.

2023-05-02 08:19 UTC, Zakari-B commented on src/View/Admin/Event/index.html.twig
> +		<div class="datas-container">
Ca ne prend jamais de s data, c'est déjà le pluriel de datum.

2023-05-02 08:19 UTC, Zakari-B commented on src/View/Component/_navbar.html.twig
Rien dans cette US n'a de lien avec ce fichier. A retirer.

2023-05-02 08:19 UTC, Zakari-B commented on src/Controller/AdminEventController.php
> +            $errors[] = "Veuillez renseigner le titre, zone obligatoire.";
"zone obligatoire" ? C'est un peu étrange comme formulation, pas vraiment nécessaire non plus.

2023-05-02 08:19 UTC, Zakari-B commented on src/Controller/AdminEventController.php
> +            $errors[] = "Veuillez renseigner l'endroit, zone obligatoire.";
le lieu serait peut être mieux que l'endroit.

2023-05-02 08:19 UTC, Zakari-B commented on src/routes.php
> +    'administration/evenements' => ['AdminEventController', 'index'],
on est sur add, pas sur le get / l'index.

2023-05-02 08:19 UTC, Zakari-B commented on src/View/Admin/Event/index.html.twig
J'ai commenté les modifications nécessaires sur ce fichier, mais on est sur l'US add, le C du crud, pas l'affichage des éléments (R du crud). Donc prenez en note puis enlevez le fichier.

2023-05-02 08:19 UTC, Zakari-B commented on src/Controller/AdminEventController.php
> +    public function index(): string
Ce n'est pas la bonne US pour cette fonction index.

2023-05-02 08:19 UTC, Zakari-B commented on public/assets/css/navbar.css
Fichier sans rapport avec l'US en cours.

2023-05-02 08:34 UTC, Justinesvr commented on src/View/Admin/Event/index.html.twig
> +		<div class="datas-container">
ba je sais bien mais ca a été validé donc j'ai été obligé de le reprendre

2023-05-02 08:35 UTC, Justinesvr commented on src/Controller/AdminEventController.php
> +                return null;
je supprime juste le return du coup?

2023-05-02 08:36 UTC, Justinesvr commented on src/View/Admin/Event/index.html.twig
> +							<th scope="row">{{ envent.id }}</th>
j'ai repris les exemples de benjamin qui ont été validé pour avoir les mêmes 'formats'!
et qu'est ce que tu entends par il y a une coquille?

2023-05-02 09:57 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-05-02 13:06 UTC, Zakari-B commented on src/Controller/AdminEventController.php
> +                return null;
Non, j'entendais par la que la redirection ne doit rien return. On met généralement un exit() parce que ça n'arrête pas nécessairement l'exécution du code et ça peut du coup donner des comportements non souhaités, donc avec exit tu es sûre que pendant que ça charge, rien d'autre ne s'exécute.
Tu peux combiner les deux avec : exit(header('Location:/Admin/Event/show?id=' . $id));

2023-05-03 09:53 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-05-03 10:30 UTC, sblondeau approved these changes

2023-05-03 12:58 UTC, merged