finish the navbar
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #4
Opened 2023-04-14 07:21 UTC by Justinesvr

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on public/assets/css/navbar.css
> +    height: 70px;
Mettre en place une variable de css dans le root pour la hauteur exemple --navbar_height : 70px

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on public/assets/css/navbar.css
> +
utilise un variable CSS dans le roor pour text-show aussi

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on public/assets/css/navbar.css
> +    text-shadow: 1px 1px 2px black;
variable css pour la aussi

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on public/assets/css/navbar.css
> +    width: 50px;
variable css à utiliser

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_navbar.html.twig
> +        <li><a href="#home">HOME</a></li>
mettre les chemins du route pour les menu

2023-04-14 07:36 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_beauceron.html.twig
> +{% block navbar %}
Mettre le contenu dans un template de page Twig mais pas en tant que composant car ce contenu n'est pas ré-utilisé

2023-04-14 08:39 UTC, Zakari-B commented
Tous les DS_Store ils doivent être retirés.

2023-04-14 08:43 UTC, sblondeau requested changes
tu ne devrais avoir que 2-3 fichier
ton twig
ton include dans layout
ton css
voire une image de logo

le reste n'a rien à faire là, je pense que tu as mergé dev dans ta branche ?
y a du code d'autres pages
beaucoup d'images de la home (donc autre US)
et ton DS_Store qui ne devrait pas etre versionné

2023-04-14 08:48 UTC, Zakari-B requested changes

2023-04-14 08:48 UTC, Zakari-B commented on src/View/Beauceron/beauceron.html.twig
> +	{% include 'Component/_navbar.html.twig' %}
Dans le layout mais pas ici.

2023-04-14 08:48 UTC, Zakari-B commented on src/View/Component/_navbar.html.twig
> +        </div>
Indentation svp.

2023-04-14 08:48 UTC, Zakari-B commented on src/View/layout.html.twig
> +	<link rel="stylesheet" href="/assets/css/style.css"> {% block stylesheet %}{% endblock %}
Block stylesheet a redescendre.

2023-04-14 08:48 UTC, Zakari-B commented
Supprimer les doublons d'images et compresser <200kb.

2023-04-15 17:57 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-15 17:57 UTC, BENJAMIN-SAUSSAYE commented on src/View/layout.html.twig
> +	<link rel="stylesheet" href="/assets/css/style.css">
Il faut retirer le lien du style  :` <link rel="stylesheet" href="/assets/css/style.css"> `
qui est deja appelé dans le head de la page

2023-04-18 09:49 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-18 10:02 UTC, Zakari-B requested changes

2023-04-18 10:02 UTC, Zakari-B commented on public/assets/css/style.css
> +    --primary: rgb(23, 20, 20);
Séparez peut être ça de la manière suivante :
--primaryColor: 23, 20, 20;
--primary: rgb(var(--primaryColor));

Ca vous permettra de maintenir une cohérence de style parce que la --navbar-color par exemple ne reprend pas votre primary.

2023-04-18 10:05 UTC, Zakari-B requested changes

2023-04-18 10:05 UTC, Zakari-B commented on public/assets/css/navbar.css
> +    --background-color: transparent;
Ce ne serait pas plutôt background-color ? Parce que la tu déclares une variable spécifique au bouton que tu n'utilises pas.

2023-04-18 10:05 UTC, Zakari-B commented on public/assets/css/navbar.css
> +    text-shadow:1px 1px 2px var(--intermadiate);
intermadiate n'existe pas.

2023-04-18 10:05 UTC, Zakari-B commented on public/assets/css/navbar.css
> +    --border-color: none;
Même remarque que précédemment, cette déclaration de variable ne me semble pas normale. Il y en a d'autres aussi plus loin dans le fichier CSS.

2023-04-18 12:28 UTC, Zakari-B requested changes

2023-04-18 12:28 UTC, Zakari-B commented on public/assets/css/style.css
>      --light: #f3f3f3;
A la ligne 6, intermediate prend un e, pas un a.

2023-04-18 14:22 UTC, closed without merging