start footer
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #5
Opened 2023-04-14 07:25 UTC by rubenk3

2023-04-15 18:02 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-15 18:02 UTC, BENJAMIN-SAUSSAYE commented on src/View/layout.html.twig
Retirer les sauts de lignes inutiles dans le fichier

2023-04-18 10:12 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-18 12:25 UTC, Zakari-B requested changes

2023-04-18 12:25 UTC, Zakari-B commented on public/assets/css/style.css
> +    --light: --primary: #181515;
Absolument pas.

2023-04-18 12:25 UTC, Zakari-B commented on src/View/Component/_footer.html.twig
> +		<div>
div inutile

2023-04-18 12:25 UTC, Zakari-B commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="/assets/css/footer.css" type="text/css">
Utiliser un @import dans style.css pour la feuille du footer.

2023-04-18 12:25 UTC, Zakari-B commented on src/View/layout.html.twig
> +    {% block footer %} {% include 'Component/_footer.html.twig' %}{% endblock %}
Les balises script étant toujours en fin de body, le footer doit être au dessus.

2023-04-18 12:25 UTC, Zakari-B commented on public/assets/css/footer.css
> +    gap: 3rem;
Utilisation de la variable spacing pour tous les gaps comme indiqué par Benjamin pour la balise img.

2023-04-18 12:26 UTC, Zakari-B commented on public/assets/css/style.css
> +    --light: --primary: #181515;
Pour info, tu viens de définir du noir en --light. Tu n'as pas à toucher à cette variable.

2023-04-21 11:14 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-21 11:14 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_footer.html.twig
> +
saut de lignes inutiles :)

2023-04-21 11:14 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_footer.html.twig
> +
idem

2023-04-21 11:14 UTC, BENJAMIN-SAUSSAYE commented on src/View/Component/_footer.html.twig
> +			<h1>Follow us</h1>
J'ai un doute sur le fait d'utiliser un H1 ici alors qu'au-dessus, tu as mis un H2 dans la div : contacts

2023-04-24 18:52 UTC, BENJAMIN-SAUSSAYE requested changes

2023-04-24 18:52 UTC, BENJAMIN-SAUSSAYE commented on public/assets/css/footer.css
> +    gap: calc(var(--spacing)*1);
Retirer le multiplier par 1 -->> calc(var(....) x1) car inutile

2023-04-25 15:05 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-25 15:44 UTC, sblondeau requested changes

2023-04-25 15:44 UTC, sblondeau commented on public/assets/images/fcb.png
pour les 3 icones facebook/insta/twitter tu trouves également des SVG sur bootstrap icon, plutot que de mettre des images

2023-04-25 15:44 UTC, sblondeau commented on src/View/Component/_footer.html.twig
> +			<h1>Follow us</h1>
effectivement, plutot un h3 ?

2023-04-25 15:44 UTC, sblondeau commented on src/View/Component/_footer.html.twig
> +			<div class='logos'>
double quotes en html

2023-04-26 13:28 UTC, BENJAMIN-SAUSSAYE submitted a review, later dismissed

2023-04-26 14:20 UTC, sblondeau requested changes
supprime les 3 images en png pour les reseaux sociaux vu que tu as mis les svg à la place, tu n'en as plus besoin ;-)

2023-04-26 15:18 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-04-26 15:35 UTC, sblondeau submitted a review, later dismissed

2023-04-28 08:51 UTC, merged