list event ok
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #51
Opened 2023-05-03 13:31 UTC by Justinesvr

2023-05-03 14:45 UTC, BENJAMIN-SAUSSAYE submitted a review, later dismissed

2023-05-03 15:06 UTC, sblondeau requested changes

2023-05-03 15:06 UTC, sblondeau commented on src/View/Admin/Event/index.html.twig
> +								<form action="/administration/event/modifier" method="POST">
pour envoyer vers la page modifer, tu dois etre en GET, puis sur cette page tu as un form qui sera en POST.
Donc ici c'est juste un lien a href=""/administration/event/modifier?id={{ event.id }}"

2023-05-04 07:40 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-05-04 07:41 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-05-04 08:33 UTC, sblondeau requested changes

2023-05-04 08:33 UTC, sblondeau commented on src/View/Admin/Event/index.html.twig
> +								<form action="/administration/event/modifier" method="GET">
non tjs pas, je veux juste un lien, aucun intéret de faire un form en GET à la place d'un lien

2023-05-04 09:45 UTC, Justinesvr commented on src/View/Admin/Event/index.html.twig
> +								<a href="/administration/evenements/supprimer?id={{ event.id }}"></a>
je crois que l'on a un problème de communication haha

2023-05-04 10:17 UTC, sblondeau approved these changes

2023-05-05 10:19 UTC, merged