S04 us19 membres admin add
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #53
Opened 2023-05-03 14:19 UTC by PAimery

2023-05-03 14:44 UTC, BENJAMIN-SAUSSAYE approved these changes

2023-05-03 15:24 UTC, sblondeau requested changes

2023-05-03 15:24 UTC, sblondeau commented on src/Controller/AdminMemberController.php
> +        $maxLength = 50;
mets 100, voire 255 ici et dans database.sql
50 c'est un peu trop juste

2023-05-03 15:24 UTC, sblondeau commented on src/View/Admin/Member/add.html.twig
> +			<input type="text" name="email" id="email" required value="{{ member.email }}">
type="email"

2023-05-04 08:14 UTC, BENJAMIN-SAUSSAYE submitted a review, later dismissed

2023-05-04 08:34 UTC, sblondeau approved these changes

2023-05-04 09:35 UTC, merged