S04U48 admin ajouter fiche nos chiens
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #59
Opened 2023-05-04 14:06 UTC by BENJAMIN-SAUSSAYE

2023-05-04 14:12 UTC, PAimery approved these changes

2023-05-04 15:40 UTC, sblondeau requested changes

2023-05-04 15:40 UTC, sblondeau commented on src/View/Admin/Relation/_form.html.twig
> +		<input type="text" name="owner" id="owner" maxlength="{{ lengthFields.MAX_LENGTH_OWNER }}" size="{{ lengthFields.MAX_LENGTH_OWNER }}" placeholder='Nom du propri&nbsp;taire...' value="{{ dog.owner ?
ok tu aimes bien te compliqué :D 
si vraiment tu veux faire ça, tu n'as pas à passer tes constantes à ta vue, car Twig peut récupérer les constantes directement (si vraiment vraiment vraiment tu veux le faire...)
je te laisse chercher dans la doc de Twig

2023-05-04 16:15 UTC, BENJAMIN-SAUSSAYE commented on src/View/Admin/Relation/_form.html.twig
> +		<input type="text" name="owner" id="owner" maxlength="{{ lengthFields.MAX_LENGTH_OWNER }}" size="{{ lengthFields.MAX_LENGTH_OWNER }}" placeholder='Nom du propri&nbsp;taire...' value="{{ dog.owner ?
constant('Namespace\\Classname::CONSTANT_NAME')

2023-05-05 08:54 UTC, PAimery approved these changes

2023-05-05 08:55 UTC, PAimery approved these changes

2023-05-05 08:56 UTC, PAimery approved these changes

2023-05-05 09:20 UTC, Zakari-B requested changes

2023-05-05 09:20 UTC, Zakari-B commented on src/Controller/AdminDogController.php
> +            $errors[] = "Le genre " . $dog['gender'] . " est incorrect, il doit correspondre " .
pourquoi mettre une concaténation entre deux phrases ? doit correspondre à l'une des valeurs [...] pas besoin de concaténer.

2023-05-05 09:20 UTC, Zakari-B commented on src/View/Admin/Relation/_form.html.twig
> +		<input type="text" name="owner" id="owner" maxlength="{{ constant('App\\Controller\\AdminDogController::MAX_LENGTH_OWNER') }}" placeholder='Nom du propri&nbsp;taire...' value=" {{ dog.owner ?? '' }
Propriétaire n'est pas bon. nbsp c'est un espace insécable, pas un accent. L'erreur se répète dans la suite du fichier.

2023-05-05 09:20 UTC, Zakari-B commented on src/View/Admin/Relation/_form.html.twig
> +		<label for="birthdate">Date de chien</label>
C'est différent d'une date d'humain ?

2023-05-05 09:33 UTC, PAimery approved these changes

2023-05-05 09:36 UTC, Zakari-B commented on src/Controller/AdminDogController.php
> +            $errors[] = "Le genre " . $dog['gender'] . " est incorrect, il doit correspondre " .
Il semblerait qu'on se soit mal compris, mon problème c'est ça :
"[...], il doit correspo**ndre " . "à l'un**e des valeurs suivantes : "

Ca sert a rien de concaténer entre deux morceaux de phrases, il n'y a pas de variable entre les deux.

2023-05-05 09:44 UTC, PAimery submitted a review, later dismissed

2023-05-05 10:26 UTC, Zakari-B approved these changes

2023-05-05 10:27 UTC, merged