ajout de l'édition d'une fiche chien côté admin
WildCodeSchool/202302-orleans-php-project2-amibeauceron pull request #62
Opened 2023-05-04 18:37 UTC by BENJAMIN-SAUSSAYE

2023-05-04 18:39 UTC, BENJAMIN-SAUSSAYE commented
J'ai dû remettre le code des deux US précédentes qui correspondent à la partie Update et Delete afin de pouvoir réaliser celle-ci.

2023-05-05 09:45 UTC, sblondeau requested changes

2023-05-05 09:45 UTC, sblondeau commented on database.sql
> +        '' << << << < HEAD = = = = = = =
aaahhhhhhh

2023-05-05 09:53 UTC, PAimery approved these changes

2023-05-05 10:24 UTC, Zakari-B requested changes

2023-05-05 10:24 UTC, Zakari-B commented on src/View/Admin/Relation/index.html.twig
> +								<form action="/administration/nos-chiens/modifier?id={{ dog.id }}" method="GET">
c'est une balise a pas un form en get pour la modification.

2023-05-05 10:24 UTC, Zakari-B commented on src/Model/DogManager.php
> +    public function insert(array $dog): int
Pourquoi il y a le insert sur le edit ?

2023-05-05 10:24 UTC, Zakari-B commented on src/Controller/AdminDogController.php
> +    public function add(): string
Pourquoi il y a tout dans le controller (add, delete...) alors que c'est le edit cette US ?

2023-05-05 10:34 UTC, PAimery submitted a review, later dismissed

2023-05-05 11:49 UTC, sblondeau requested changes
je la passe mais il ne faut PAS reprendre le code d'une US qui n'est pas encore validée
mieux vaut attendre que la 1ere soit passée pour récupérer la suivante, en attendant travailler sur autre chose

2023-05-05 11:50 UTC, sblondeau submitted a review, later dismissed

2023-05-05 12:12 UTC, merged